package dev.romeo.btctradingengine.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.info.GitProperties;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Logs which build is running, once the context is up: the same version, commit and build time
 * /actuator/info reports. Both files are generated by the build (META-INF/build-info.properties and
 * git.properties), so nothing here is kept in sync by hand.
 *
 * <p>Running from an IDE or from a source tree without the packaging step leaves either file out;
 * the provider is then empty and the line degrades to what is known.
 */
@Component("buildVersionLogger")
public class BuildVersionLogger {
    private static final Logger logger = LoggerFactory.getLogger(BuildVersionLogger.class);

    private final ObjectProvider<BuildProperties> build;
    private final ObjectProvider<GitProperties> git;

    public BuildVersionLogger(
            ObjectProvider<BuildProperties> build, ObjectProvider<GitProperties> git) {
        this.build = build;
        this.git = git;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void logVersion() {
        logger.info("Running {}", describe());
    }

    /** The one-line build identity. */
    public String describe() {
        BuildProperties buildProperties = build.getIfAvailable();
        GitProperties gitProperties = git.getIfAvailable();
        StringBuilder line = new StringBuilder();
        if (buildProperties == null) {
            line.append("btc-trading-engine (development build, no build-info.properties)");
        } else {
            line.append(buildProperties.getName())
                    .append(' ')
                    .append(buildProperties.getVersion())
                    .append(" built ")
                    .append(buildProperties.getTime());
        }
        if (gitProperties != null) {
            line.append(" from commit ")
                    .append(gitProperties.getShortCommitId())
                    .append(" (")
                    .append(gitProperties.getBranch())
                    .append(')');
        }
        return line.toString();
    }
}
