name: Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: btctradingengine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
          cache-dependency-path: btctradingengine/pom.xml

      - name: Build
        run: ./mvnw clean package -DskipTests