#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#
name: Qodana

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - main
      - develop
      - feat/reconnect-safe-binance

jobs:
  qodana:
    name: Qodana Code Quality
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: --linter jetbrains/qodana-jvm-community:2026.1
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true